### ISSUE TITLE
Sample does not work on 2.3 device

### ISSUE THREAD

**Issue by jorgenstorlie** [Cheesebaron/SlidingMenuSharp#2]
Are you going to make a sample with LegacyBar or/and ActionBarSherlock?

**Comment by Cheesebaron** [comment]
I will make a sample with LegacyBar soon, however I suspect that Sliding Content will not work. Will have a look :)

**Comment by jorgenstorlie** [comment]
What is soon, days, weeks?
I´m working on a demo for a customer right now, so  I need to know if I should fix it myself.
(Does not need a complete sample)

Do you think the combination SlidingMenuSharp/LegacyBar would be a good solution?
My alternative is ActionBarSherlock with Slindingmenu.

**Comment by Cheesebaron** [comment]
Don't wait for me to fix the issue, I love contributions; however I will have a look during this week, but I can't make any promises.

Depends on your needs really. LegacyBar is still missing some features that Sherlock has, mainly the search view and an interface for adding Tabs. This SlidingMenu is still very very fresh and needs some work to bring it up to the native counterpart.

**Comment by jorgenstorlie** [comment]
Any progress on LegacyBar sample?

**Comment by dvmorris** [comment]
Does this project support Android prior to 3.1, or are you still looking for a user contribution?

**Comment by Cheesebaron** [comment]
The project itself, just like the native Java counterpart runs on Android prior to 3.1. However the sample does not. You are welcome to make a sample using one of the Support ActionBars.

**Comment by dvmorris** [comment]
Any tips on how to get started on that? I'm new to Xamarin.Android development, so I'm not really familiar with Support ActionBars.

**Comment by rogerfar** [comment]
Cheesebaron did you manage to create a 2.3 sample? I am also stuck here on some style.xml things.

**Comment by Cheesebaron** [comment]
Just download the ActionBarSherlock component and that is basically it. I am not going to make a sample because I simply do not have the time for it.
